name: Clean Git History and Update Themes
on:
  schedule:
  - cron: '00 23 * * 04'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean Repo
        run: |
          #!/bin/bash
          set -x 
          #echo on
          sudo apt install git default-jre -y 
          java -version
          git clone --mirror https://github.com/Osmium-Linux/rtl88-Themes-main.git
          cd rtl88-Themes-main.git
          wget https://repo1.maven.org/maven2/com/madgag/bfg/1.13.0/bfg-1.13.0.jar
          java -jar bfg-*.jar --strip-blobs-bigger-than 1M 
          git reflog expire --expire=now --all && git gc --prune=now --aggressive
          rm bfg-*.jar
      - name: Commit to repository
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          COMMIT_MSG: |
            <Clean Git History>
            skip-checks: true
        run: |
          # Hard-code user configuration
          #!/bin/bash
          set -x 
          #echo on
          pwd
          cd rtl88-Themes-main.git
          echo 1
          git config user.email "tysayahi@gmail.com"
          echo 2
          git config user.name "Eile Kerning"
          echo 3
          # Update origin with token
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          echo 4
          # Checkout the branch so we can push back to it
          echo 6 
          echo git add .
          git config --unset remote.origin.mirror
          echo 7
          git push -f origin +master
      - name: Delete Old Themes
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          COMMIT_MSG: |
            Remove old Themes
            skip-checks: true
        run: |
          set -x 
          #echo on
          git clone https://github.com/Osmium-Linux/rtl88-Themes-main.git --depth 1
          # Hard-code user configuration
          pwd
          mkdir ./.github/
          mv ./rtl88-Themes-main/.github/* ./.github/
          rm -rf ./rtl88-Themes-main/*
          mv ./.github/* ./rtl88-Themes-main/.github/
          cd rtl88-Themes-main
          git config user.email "tysayahi@gmail.com"
          git config user.name "Eile Kerning"
          # Update origin with token
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          # Checkout the branch so we can push back to it
          git checkout master
          git add .
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)
